-- stolen from https://github.com/KevinPalowa/nvim/

require("antheiz.options")
require("antheiz.autocmds")
require("antheiz.keymaps")
require("antheiz.plugins")
require("antheiz.colorscheme")
require("antheiz.cmp")
require("antheiz.lsp")
require("antheiz.telescope")
require("antheiz.presence")
require("antheiz.toggleterm")
require("antheiz.lualine")
require("antheiz.autopairs")
require("antheiz.comment")
require("antheiz.gitsigns")
require("antheiz.neotree")
require("antheiz.treesitter")
require("antheiz.bufferline")
require("antheiz.indentline")
require("antheiz.trouble")
require("antheiz.alpha")
require("antheiz.project")
require("antheiz.colorizer")
require("antheiz.whichkey")
